CREATE TABLE IF NOT EXISTS metadata(
    id INTEGER PRIMARY KEY,
    fpath TEXT NOT NULL UNIQUE,
    fhash TEXT NOT NULL 
);
CREATE TABLE IF NOT EXISTS tags(
    id INTEGER PRIMARY KEY,
    tagname TEXT NOT NULL UNIQUE,
    tagdescription TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS albums(
    id INTEGER PRIMARY KEY,
    albumname TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS prefs(
    id INTEGER PRIMARY KEY,
    pref TEXT NOT NULL UNIQUE,
    val TEXT NOT NULL
);